### ISSUE TITLE
Active Noise Cancellation Paper

### ISSUE THREAD

**Issue by Durak06** [akym/ActiveNoiseCancellation#1]
Hi,

Could you please send me the original active noise cancellation paper? For instance, I can't see the author.
I want to use this paper on my project. 

Regards
Durak

**Comment by akym** [comment]
Hi Durak,
You can use the paper, it was an assignment to fulfill my college credits, whatever is in the paper is pretty basic and you can use it without any credits to me or any author, for detailed and more accurate information refer to the papers listed in the bibliography.

Good day.
